<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Kontent.ai ASP.NET Core SDK</Description>
    <PackageTags>kontent-ai;mvc;aspnet;aspnetmvc</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kontent.Ai.Delivery.Abstractions" />
    <PackageReference Include="Kontent.Ai.Urls" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Kontent.Ai.AspNetCore.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
